(defvar *ph* (/ (+ (sqrt 5) 1) 2))
(defvar *rph* (/ 1 *ph*))
(defun dodecahedron ()  
"Genenrate dodecahedron base Cartesian coordinates"
( list
                         (list 1 1 -1)
                         (list 1 1 1)
                         (list 1 -1 1)
                         (list -1 1 1)
                         (list -1 -1 1)
                         (list 1 -1 -1)
                         (list -1 1 -1)
                         (list -1 -1 -1)
                         (list 0 *rph* *ph*)
                         (list 0 (* -1 *rph*) *ph*)
                         (list 0 *rph* (* -1 *ph*))
                         (list 0 (* -1 *rph*) (* -1 *ph*))
                         (list *rph* *ph* 0)
                         (list (* -1 *rph*) *ph* 0)
                         (list *rph* (* -1 *ph*) 0)
                         (list (* -1 *rph*) (* -1 *ph*) 0)
                         (list *ph* 0 *rph*)
                         (list (* -1 *ph*) 0 *rph*)
                         (list *ph* 0 (* -1 *rph*))
                         (list (* -1 *ph*) 0 (* -1 *rph*))
                   )
  )
